    ctrl.Rule(suit['normal'] & (chips['low'] | boardQ['high']), play['all-in']),
    ctrl.Rule(suit['normal'] & (chips['normal'] | boardQ['normal']) & bet['low'], play['call']),
    ctrl.Rule(suit['normal'] & (chips['normal'] | boardQ['normal']) & bet['normal'], play['call']),
    ctrl.Rule(suit['normal'] & (chips['normal'] | boardQ['normal']) & bet['high'], play['fold']),
    ctrl.Rule(suit['normal'] & (chips['high'] | boardQ['low']) & bet['low'], play['all-in']),
    ctrl.Rule(suit['normal'] & (chips['high'] | boardQ['low']) & bet['normal'], play['call']),
    ctrl.Rule(suit['normal'] & (chips['high'] | boardQ['low']) & bet['high'], play['fold']),
    ctrl.Rule(suit['high'] & (chips['low'] | boardQ['high']), play['all-in']),
    ctrl.Rule(suit['high'] & (chips['high'] | boardQ['low']), play['all-in']),
    ctrl.Rule(suit['high'] & (chips['normal'] | boardQ['normal']) & bet['low'], play['small raise']),
    ctrl.Rule(suit['high'] & (chips['normal'] | boardQ['normal']) & bet['normal'], play['call']),
    ctrl.Rule(suit['high'] & (chips['normal'] | boardQ['normal']) & bet['high'], play['all-in']),